sudo: required 
services:
  - docker


before_install:
  - docker build -t jainnrishabh/docker-react -f Dockerfile.dev .
  
script:
  - docker run jainnrishabh/docker-react npm run test -- --coverage
